version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@1.0.0

executors:
  builder:
    docker:
      - image: circleci/node:12.16.1-buster-browsers
    working_directory: ~/app

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci --no-audit
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Run Tests
          command: |
            set -e
            npm test -- --maxWorkers=2
      - run: NODE_ENV=production npm run build
      - run: |
          DATE=$(date '+%Y-%m-%d')
          export BUILD_NUMBER=${DATE}.${CIRCLE_BUILD_NUM}
          export GIT_REF=${CIRCLE_SHA1}
          export GIT_DATE=${DATE}
          npm run record-build-info
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build
            - build-info.json

  integration_tests:
    working_directory: ~/app
    docker:
      - image: circleci/node:12.16.1-buster-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Run the node app.
          command: npm run start-feature
          background: true
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "keyworker-specs/build.gradle" }}
      - run:
          name: Run Integration Tests
          command: ./gradlew build
      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - /home/circleci/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "keyworker-specs/build.gradle" }}
          paths:
            - /home/circleci/.gradle/caches
      - store_artifacts:
          path: keyworker-specs/build/reports
          destination: integration/spock
      - store_artifacts:
          path: keyworker-specs/build/geb-reports
          destination: integration/geb
      - store_test_results:
          path: keyworker-specs/build/test-results

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - integration_tests:
          requires:
            - build
      - hmpps/build_docker:
          name: build_docker
          image_name: "quay.io/hmpps/omic-ui"
          filters:
            branches:
              only:
                - master
      - hmpps/deploy_env:
          chart_name: manage-key-workers
          release_name: manage-key-workers
          name: deploy_dev
          env: "dev"
          filters:
            branches:
              only:
                - master
          requires:
            - build_docker
            - integration_tests
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          chart_name: manage-key-workers
          release_name: manage-key-workers
          name: deploy_preprod
          env: "preprod"
          context: manage-key-workers-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          chart_name: manage-key-workers
          release_name: manage-key-workers
          name: deploy_prod
          env: "prod"
          slack_notification: true
          context: manage-key-workers-prod
          requires:
            - request-prod-approval

  scheduled:
    triggers:
      - schedule:
          cron: '0 7 * * 1-5'
          filters:
            branches:
              only:
                - master
    jobs:
      - hmpps/npm_security_audit
