# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: docker.io/mojdigitalstudio/omic-ui
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_whitelist: true
  host: manage-key-workers.service.justice.gov.uk
  cert_secret: manage-key-workers-cert
  path: /

env:
  API_ENDPOINT_URL: https://gateway.prod.nomis-api.service.hmpps.dsd.io/elite2api/
  OAUTH_ENDPOINT_URL: https://gateway.prod.nomis-api.service.hmpps.dsd.io/auth/
  KEYWORKER_API_URL: https://keyworker-api.service.hmpps.dsd.io/
  NN_ENDPOINT_URL: https://notm.service.hmpps.dsd.io/
  PRISON_STAFF_HUB_UI_URL: https://prisonstaffhub.service.hmpps.dsd.io/
  HMPPS_COOKIE_NAME: hmpps-session-prod
  NODE_ENV: production
  MAINTAIN_ROLES_ENABLED: "true"
  KEYWORKER_PROFILE_STATS_ENABLED: "true"
  KEYWORKER_DASHBOARD_STATS_ENABLED: "true"
  REMOTE_AUTH_STRATEGY: "true"
  WEB_SESSION_TIMEOUT_IN_MINUTES: "60"

whitelist:
  office: "217.33.148.210/32"
  quantum: "62.25.109.197/32"
  quantum_alt: "212.137.36.230/32"
  health-kick: "35.177.252.195/32"
  digitalprisons1: "52.56.112.98/32"
  digitalprisons2: "52.56.118.154/32"
  mojvpn: "81.134.202.29/32"
  j5-phones-1: "35.177.125.252/32"
  j5-phones-2: "35.177.137.160/32"
  sodexo-northumberland: "88.98.48.10/32"
  thameside-private-prison: "217.22.14.151/32"
  ark-nps-hmcts-ttp1: "195.59.75.0/24"
  ark-nps-hmcts-ttp2: "194.33.192.0/25"
  ark-nps-hmcts-ttp3: "194.33.193.0/25"
  ark-nps-hmcts-ttp4: "194.33.196.0/25"
  ark-nps-hmcts-ttp5: "194.33.197.0/25"
  oakwood: "194.176.200.113/32"
