# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/manage-key-workers
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  host: dev.manage-key-workers.service.justice.gov.uk
  cert_secret: manage-key-workers-cert
  path: /

env:
  API_ENDPOINT_URL: https://api-dev.prison.service.justice.gov.uk
  OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
  KEYWORKER_API_URL: https://keyworker-api-dev.prison.service.justice.gov.uk
  NN_ENDPOINT_URL: https://digital-dev.prison.service.justice.gov.uk/
  PRISON_STAFF_HUB_UI_URL: https://digital-dev.prison.service.justice.gov.uk/
  HMPPS_COOKIE_NAME: hmpps-session-dev
  NODE_ENV: production
  MAINTAIN_ROLES_ENABLED: "true"
  KEYWORKER_PROFILE_STATS_ENABLED: "true"
  KEYWORKER_DASHBOARD_STATS_ENABLED: "true"
  REMOTE_AUTH_STRATEGY: "true"
  WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
  TOKENVERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
  TOKENVERIFICATION_API_ENABLED: true
  REDIS_ENABLED: true
  SUPPORT_URL: https://support-dev.hmpps.service.justice.gov.uk/
  COMPLEXITY_OF_NEED_URI: https://complexity-of-need-staging.hmpps.service.justice.gov.uk
